export const filterOptions = {
  genres: [
    { id: 4, name: "Action", slug: "action" },
    { id: 3, name: "Adventure", slug: "adventure" },
    { id: 5, name: "RPG", slug: "role-playing-games-rpg" },
    { id: 2, name: "Shooter", slug: "shooter" },
    { id: 7, name: "Puzzle", slug: "puzzle" },
    { id: 10, name: "Strategy", slug: "strategy" },
    { id: 11, name: "Sports", slug: "sports" },
    { id: 6, name: "Fighting", slug: "fighting" },
    { id: 14, name: "Simulation", slug: "simulation" },
    { id: 15, name: "Arcade", slug: "arcade" },
    { id: 19, name: "Family", slug: "family" },
    { id: 28, name: "Board Games", slug: "board-games" },
    { id: 17, name: "Card", slug: "card" },
    { id: 29, name: "Indie", slug: "indie" },
    { id: 30, name: "Casual", slug: "casual" },
    { id: 31, name: "Racing", slug: "racing" },
    { id: 32, name: "Massively Multiplayer", slug: "massively-multiplayer" },
    { id: 33, name: "Platformer", slug: "platformer" },
    { id: 34, name: "Educational", slug: "educational" },
    { id: 35, name: "Stealth", slug: "stealth" },
    { id: 36, name: "Battle Royale", slug: "battle-royale" },
    { id: 37, name: "MMORPG", slug: "mmorpg" },
    { id: 38, name: "Metroidvania", slug: "metroidvania" },
    { id: 39, name: "Roguelike", slug: "roguelike" },
    { id: 40, name: "Visual Novel", slug: "visual-novel" },
    { id: 41, name: "Tactical", slug: "tactical" },
    { id: 42, name: "Sandbox", slug: "sandbox" },
    { id: 43, name: "Real Time Strategy", slug: "real-time-strategy" },
    { id: 44, name: "Turn-Based Strategy", slug: "turn-based-strategy" },
    { id: 45, name: "Hack and Slash", slug: "hack-and-slash" },
    { id: 46, name: "Survival Horror", slug: "survival-horror" },
    { id: 47, name: "Rhythm", slug: "rhythm" },
    { id: 48, name: "Music", slug: "music" },
    { id: 49, name: "Party", slug: "party" },
    { id: 50, name: "Trivia", slug: "trivia" },
    { id: 51, name: "Pinball", slug: "pinball" },
    { id: 52, name: "Fitness", slug: "fitness" },
    { id: 53, name: "Dungeon Crawler", slug: "dungeon-crawler" },
    { id: 54, name: "MOBA", slug: "moba" },
    { id: 55, name: "4X", slug: "4x" },
    { id: 56, name: "Artillery", slug: "artillery" },
    { id: 57, name: "Beat 'em up", slug: "beat-em-up" },
    { id: 58, name: "Idler", slug: "idler" },
    { id: 59, name: "Tycoon", slug: "tycoon" },
  ],
  platforms: [
    { id: 4, name: "PC", slug: "pc" },
    { id: 187, name: "PlayStation 5", slug: "playstation5" },
    { id: 18, name: "PlayStation 4", slug: "playstation4" },
    { id: 16, name: "PlayStation 3", slug: "playstation3" },
    { id: 15, name: "PlayStation 2", slug: "playstation2" },
    { id: 27, name: "PlayStation", slug: "playstation1" },
    { id: 186, name: "Xbox Series S/X", slug: "xbox-series-x" },
    { id: 1, name: "Xbox One", slug: "xbox-one" },
    { id: 14, name: "Xbox 360", slug: "xbox360" },
    { id: 80, name: "Xbox", slug: "xbox-old" },
    { id: 7, name: "Nintendo Switch", slug: "nintendo-switch" },
    { id: 10, name: "Wii U", slug: "wii-u" },
    { id: 11, name: "Wii", slug: "wii" },
    { id: 105, name: "GameCube", slug: "gamecube" },
    { id: 83, name: "Nintendo 64", slug: "nintendo-64" },
    { id: 105, name: "GameCube", slug: "gamecube" },
    { id: 8, name: "Nintendo 3DS", slug: "nintendo-3ds" },
    { id: 9, name: "Nintendo DS", slug: "nintendo-ds" },
    { id: 13, name: "Nintendo DSi", slug: "nintendo-dsi" },
    { id: 24, name: "Game Boy Advance", slug: "gba" },
    { id: 43, name: "Game Boy Color", slug: "game-boy-color" },
    { id: 26, name: "Game Boy", slug: "game-boy" },
    { id: 19, name: "PS Vita", slug: "ps-vita" },
    { id: 17, name: "PSP", slug: "psp" },
    { id: 3, name: "iOS", slug: "ios" },
    { id: 21, name: "Android", slug: "android" },
    { id: 5, name: "macOS", slug: "macos" },
    { id: 6, name: "Linux", slug: "linux" },
    { id: 167, name: "Genesis", slug: "genesis" },
    { id: 119, name: "SEGA CD", slug: "sega-cd" },
    { id: 107, name: "Sega Saturn", slug: "sega-saturn" },
    { id: 23, name: "Atari 2600", slug: "atari-2600" },
    { id: 31, name: "Atari 5200", slug: "atari-5200" },
    { id: 28, name: "Atari 7800", slug: "atari-7800" },
    { id: 22, name: "Atari Flashback", slug: "atari-flashback" },
    { id: 25, name: "Atari 8-bit", slug: "atari-8-bit" },
    { id: 12, name: "Neo Geo", slug: "neo-geo" },
    { id: 79, name: "SNES", slug: "snes" },
    { id: 49, name: "NES", slug: "nes" },
    { id: 55, name: "Classic Macintosh", slug: "macintosh" },
    { id: 41, name: "Apple II", slug: "apple-ii" },
  ],
  tags: [
    { id: 31, name: "Multiplayer", slug: "multiplayer" },
    { id: 32, name: "Singleplayer", slug: "singleplayer" },
    { id: 33, name: "Co-op", slug: "co-op" },
    { id: 34, name: "Open World", slug: "open-world" },
    { id: 35, name: "Survival", slug: "survival" },
    { id: 36, name: "Sandbox", slug: "sandbox" },
    { id: 37, name: "First-Person", slug: "first-person" },
    { id: 38, name: "Third-Person", slug: "third-person" },
    { id: 39, name: "Horror", slug: "horror" },
    { id: 40, name: "Sci-fi", slug: "sci-fi" },
    { id: 41, name: "Fantasy", slug: "fantasy" },
    { id: 42, name: "Zombies", slug: "zombies" },
    { id: 43, name: "VR", slug: "vr" },
    { id: 44, name: "Retro", slug: "retro" },
    { id: 45, name: "Story Rich", slug: "story-rich" },
    { id: 46, name: "Atmospheric", slug: "atmospheric" },
    { id: 47, name: "2D", slug: "2d" },
    { id: 48, name: "3D", slug: "3d" },
    { id: 49, name: "Pixel Graphics", slug: "pixel-graphics" },
    { id: 50, name: "Exploration", slug: "exploration" },
    { id: 51, name: "Comedy", slug: "comedy" },
    { id: 52, name: "MMO", slug: "mmo" },
    { id: 53, name: "Battle Royale", slug: "battle-royale" },
    { id: 54, name: "Cyberpunk", slug: "cyberpunk" },
    { id: 55, name: "Roguelike", slug: "roguelike" },
    { id: 56, name: "Metroidvania", slug: "metroidvania" },
    { id: 57, name: "Party", slug: "party" },
    { id: 58, name: "Stealth", slug: "stealth" },
    { id: 59, name: "Puzzle", slug: "puzzle" },
    { id: 60, name: "Real Time Strategy", slug: "real-time-strategy" },
    { id: 61, name: "Tactical", slug: "tactical" },
    { id: 62, name: "Military", slug: "military" },
    { id: 63, name: "Space", slug: "space" },
    { id: 64, name: "Post-apocalyptic", slug: "post-apocalyptic" },
    { id: 65, name: "Dystopian", slug: "dystopian" },
    { id: 66, name: "Medieval", slug: "medieval" },
    { id: 67, name: "Historical", slug: "historical" },
    { id: 68, name: "Mystery", slug: "mystery" },
    { id: 69, name: "Detective", slug: "detective" },
    { id: 70, name: "Crafting", slug: "crafting" },
    { id: 71, name: "Building", slug: "building" },
    { id: 72, name: "Physics", slug: "physics" },
    { id: 73, name: "Procedural Generation", slug: "procedural-generation" },
    { id: 74, name: "Perma Death", slug: "perma-death" },
    { id: 75, name: "Loot", slug: "loot" },
    { id: 76, name: "Class-Based", slug: "class-based" },
    {
      id: 77,
      name: "Character Customization",
      slug: "character-customization",
    },
    { id: 78, name: "Choices Matter", slug: "choices-matter" },
    { id: 79, name: "Narrative", slug: "narrative" },
    { id: 80, name: "Cinematic", slug: "cinematic" },
    { id: 81, name: "Isometric", slug: "isometric" },
    { id: 82, name: "Top-Down", slug: "top-down" },
    { id: 83, name: "Twin Stick Shooter", slug: "twin-stick-shooter" },
    { id: 84, name: "Bullet Hell", slug: "bullet-hell" },
    { id: 85, name: "Rhythm", slug: "rhythm" },
    { id: 86, name: "Music", slug: "music" },
    { id: 87, name: "Farming", slug: "farming" },
    { id: 88, name: "Life Sim", slug: "life-sim" },
    { id: 89, name: "Cooking", slug: "cooking" },
    { id: 90, name: "Parkour", slug: "parkour" },
    { id: 91, name: "Vehicular Combat", slug: "vehicular-combat" },
    { id: 92, name: "Dating Sim", slug: "dating-sim" },
    { id: 93, name: "Psychological Horror", slug: "psychological-horror" },
    { id: 94, name: "Time Travel", slug: "time-travel" },
    { id: 95, name: "Aliens", slug: "aliens" },
    { id: 96, name: "Dinosaurs", slug: "dinosaurs" },
    { id: 97, name: "Vampire", slug: "vampire" },
    { id: 98, name: "Zombie Survival", slug: "zombie-survival" },
    { id: 99, name: "Battle Arena", slug: "battle-arena" },
    { id: 100, name: "Hero Shooter", slug: "hero-shooter" },
    { id: 101, name: "eSports", slug: "esports" },
    { id: 102, name: "Competitive", slug: "competitive" },
    { id: 103, name: "PvP", slug: "pvp" },
    { id: 104, name: "PvE", slug: "pve" },
    { id: 105, name: "Tower Defense", slug: "tower-defense" },
    { id: 106, name: "Card Game", slug: "card-game" },
    { id: 107, name: "Deck Building", slug: "deck-building" },
    { id: 108, name: "Tabletop", slug: "tabletop" },
  ],
  developers: [
    { id: 1, name: "Ubisoft", slug: "ubisoft" },
    { id: 2, name: "Electronic Arts", slug: "electronic-arts" },
    { id: 3, name: "Rockstar Games", slug: "rockstar-games" },
    { id: 4, name: "Bethesda Softworks", slug: "bethesda-softworks" },
    { id: 5, name: "CD Projekt Red", slug: "cd-projekt-red" },
    { id: 6, name: "Square Enix", slug: "square-enix" },
    { id: 7, name: "Valve", slug: "valve" },
    { id: 8, name: "Capcom", slug: "capcom" },
    { id: 9, name: "Activision", slug: "activision" },
    { id: 10, name: "Nintendo", slug: "nintendo" },
    {
      id: 11,
      name: "Sony Interactive Entertainment",
      slug: "sony-interactive-entertainment",
    },
    { id: 12, name: "Blizzard Entertainment", slug: "blizzard-entertainment" },
    { id: 13, name: "Epic Games", slug: "epic-games" },
    {
      id: 14,
      name: "Bandai Namco Entertainment",
      slug: "bandai-namco-entertainment",
    },
    { id: 15, name: "SEGA", slug: "sega" },
    {
      id: 16,
      name: "Warner Bros. Interactive Entertainment",
      slug: "warner-bros-interactive-entertainment",
    },
    { id: 17, name: "FromSoftware", slug: "fromsoftware" },
    { id: 18, name: "Mojang Studios", slug: "mojang-studios" },
    { id: 19, name: "Riot Games", slug: "riot-games" },
    { id: 20, name: "Bluehole Studio", slug: "bluehole-studio" },
  ],
};
